App_Login/urls.py
from django.urls import path
from App_Login import views

app_name="App_Login"

urlpatterns = [
    path('signup/',views.sign_up,name="signup"),
    path('login/',views.login_page,name="login"),
    path('edit/',views.edit_profile,name="edit",),
    path('logout/',views.logout_user,name="logout"),
    path('profile/',views.profile,name="profile"),
    path('user/<username>/',views.user,name="user"),
    path('follow/<username>/',views.follow,name="follow"),
    path('unfollow/<username>/',views.unfollow,name="unfollow"),
]

App_Posts/urls.py
from django.urls import path
from App_Posts import views

app_name='App_Posts'

urlpatterns = [
    path('',views.home,name='home'),
    path('like/<pk>/',views.liked,name="liked"),
    path('unlike/<pk>/',views.unliked,name="unliked"),
]

first/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns
from App_Posts import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('App_Login.urls')),
    path('post/',include('App_Posts.urls')),
    path('',views.home,name='home'),
]


urlpatterns +=staticfiles_urlpatterns()
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% comment %} link sheet {% endcomment %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.2.1/dist/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha384-nPxGHt5w03eU6sMf7hhqfsb6NV6IEXw8VQJ2wbPcQfV0Rc3l1z9+znV3uUn1he3S" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    
    <title>{% block title %}Social {% endblock %}</title>
    <div class="container" style="padding-top:30px">
    {%block body_block%}
    {%endblock%}
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

templates/navbar.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% comment %} link sheet {% endcomment %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.2.1/dist/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha384-nPxGHt5w03eU6sMf7hhqfsb6NV6IEXw8VQJ2wbPcQfV0Rc3l1z9+znV3uUn1he3S" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    
    <title>{% block title %}Social {% endblock %}</title>
    <style>
        .form-inline {
          display: flex;
          align-items: center; /* Center items vertically */
        }
      
        .form-inline input {
          width: 150px; /* Adjust the width as needed */
          padding: 0.25rem; /* Adjust padding as needed */
          font-size: 0.8rem; /* Adjust font size as needed */
        }
      
        .form-inline button {
          font-size: 0.8rem; /* Adjust font size as needed */
        }
      </style>
      
        {%block css_block%}
        {%endblock%}
</head>
<body>
    <nav class="nabvar navbar-expand-sm bg-light navbar-light">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{%url 'App_Posts:home'%}">Home</a>
            </li> 
            &nbsp; &nbsp;&nbsp;&nbsp;
              <form class="form-inline" method="GET">
                <input class="form-control" type="text" name="search" placeholder="Search">
                <button class="btn btn-success" type="submit">Search</button>
              </form>
              
            <li class="nav-item">
                <a class="nav-link" href="{%url 'App_Login:logout'%}">Logout</a>
            </li>
            <li class="nav-item">
                {%if user.user_profile.profile_pic%}
                <a class="nav-link" href="{%url 'App_Login:profile'%}"> <img src="/media/{{user.user_profile.profile_pic}}" width="40px" height="40px" class="rounded-circle" > </a>
                {%else%}
                <a class="nav-link" href="{%url 'App_Login:profile'%}"> <img src="/media/default.png" width="40px" height="40px" class="rounded-circle" > </a>
                {%endif%}
            </li>
    </ul>
</nav>
    <div class="container" style="padding-top:30px">
    {%block body_block%}
    {%endblock%}
    </div>
 
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>